### ISSUE TITLE
Result of run() seems to be undefined even when prepared properly.

### ISSUE THREAD

**Issue by jimthedev** [dai-shi/react-suspense-fetch#1]
If you create a new todo in https://codesandbox.io/s/ecstatic-dawn-l4337 you'll see an error message for the todo name. If you check the console you will see that the mutationResult is coming back as undefined from run() on line 47 of NewTodo.tsx. I don't think this should be the case.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/ecstatic-dawn-l4337

> ModuleNotFoundError
Could not find module in path: './CreateBackend' relative to '/src/NewItem.tsx'

Can you fix this please?

And, I understand what is the confusion. It's not stated anywhere, but `prepare` creates an object that can only `run` once.
In your use case, you want to `prepare` a new object in `onClick`, which means `prefetch` is fine. `prefetch` is simply `prepare` + `run`.

**Comment by jimthedev** [comment]
Ok I think it should be all fixed now! Thanks for your help: https://codesandbox.io/s/ecstatic-dawn-l4337

**Comment by dai-shi** [comment]
Wonderful!
