### ISSUE TITLE
Infinite loop when input is an object

### ISSUE THREAD

**Issue by volkanunsal** [dai-shi/react-suspense-fetch#16]
I'm running into an issue where `get` doesn't use the cache if the argument input is an object. It must be because the `get` method on `WeakMap` uses object identity, right? Is there any way around this? Serializing the object perhaps?

**Comment by dai-shi** [comment]
I understand this behavior is not very intuitive, but I wanted something that works with JS garbage collection.
In the current design, you need to serialize it, or memoize it to keep object identity.

**Comment by volkanunsal** [comment]
Can you give an example of how to memoize the arguments?

**Comment by dai-shi** [comment]
In react, the easiest is `useMemo`.
Otherwise, reselect or proxy-memoieze would help.
A naive `Map` can do too, but if it's only for react-suspense-fetch, serialization should be easier.
A counter question, can you provide a small codesandbox example, that we can work on as a concrete idea?

**Comment by volkanunsal** [comment]
You mean a code example to iterate on this issue or on the PR? The code that caused infinite loop was:

```js
const getProject = () => projects.get({ id: profile.id, token: profile.nextToken });
```

I ended up serializing the arguments.

**Comment by dai-shi** [comment]
I mean a toy react app in codesandbox. but, never mind if that's a hustle.

`useMemo` would be used something like this:
```js
const getProject = (key) => projects.get({ id: profile.id, token: profile.nextToken });

const Component = ({ profile }) => {
  const key = useMemo(() => ({ id: profile.id, token: profile.nextToken }), [profile.id, profile.nextToken])
  getProject(key)
  ...
```

I think if serialization works for you, it's good. You only need to evict it once it's no longer needed, depending on the use case.

**Comment by Nate-Wilkins** [comment]
Is there a better example on how to handle multiple inputs?

I'm trying to prefetch and then get from the cache but running into the infinite retrieval issue as well.

**Comment by dai-shi** [comment]
we keep configurable cache type for the moment. closing.
