### ISSUE TITLE
Support cancellation

### ISSUE THREAD

**Issue by tom-sherman** [dai-shi/react-suspense-fetch#42]
If a component rerenders the store will refetch without cancelling the in-flight fetch.

Just spam the button on this demo: https://codesandbox.io/s/react-suspense-fetch-spam-ibqdlp?file=/src/App.js

Is it possible to add query cancellation to this library? I'm assuming not but I could be wrong

**Comment by tom-sherman** [comment]
I think the only way of achieving this would be to add some form of query key a la React Query which would change the API to something like `store.get(key, input)`. The FetchStore could then pass a signal into the FetchFunc.

**Comment by tom-sherman** [comment]
> When do you want not to cancel fetching?

This is an interesting question. I think calling `.get()` across in multiple component instances wouldn't trigger cancellation. Conversely maybe it makes sense to always cancel when calling `.get()` inside the same component instance.

I don't know how this would look tho it for sure wouldn't use user-provided keys as these would be the same across all component instances.

**Comment by tom-sherman** [comment]
For example:

```jsx
function User({ id }) {
  store.get(id)
}

// This should cancel on each new `id` passed as a prop
<User id={id} />

// This should allow fetching both users in parallel, but if id1 or id2 changes then the relevant query should be cancelled
<>
  <User id={id1} />
  <User id={id2} />
</>
```

**Comment by tom-sherman** [comment]
Hmm, I can't get my head around how prefetch orchestrates cancelation 🤔 

Do you mean that cancelation should only trigger by calling `prefetch()` with different inputs?

**Comment by dai-shi** [comment]
`get()` invokes `prefetch()` internally, but that's like an escape hatch. (For example, we might not have a chance to prefetch for the initial render.)
